name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-06"


[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiODg1YjRkMjgtZGFiZi00ZjNmLWE1MGMtOTNiZjczYjkwNDk3IiwidGVuYW50X2lkIjoiMGYwYWQzNTM5OWQ1NDg1YWI4ZDkwOTg4YjNiYjA3MGNlOTFmNjFlYjNjZWIyZWMyMzQyZDBjM2YzYTU4YWNkOSIsImludGVybmFsX3NlY3JldCI6IjlhMWRkODkxLWNhNTctNGIzZS05MWI4LTViMTlkYzY3M2RmYiJ9.4L_q1WTzvHYefFVCiU3UgzrIbpI8qv8jux4q0vtAcO0"
JWT_SECRET="THIS_IS_SECRET"